### ISSUE TITLE
yolov10 image size when training

### ISSUE THREAD

**Issue by hengrui0516** [ppaanngggg/yolo-doclaynet#1]
I want to know your setting about image size when training yolov10 with doclaynet

**Comment by hengrui0516** [comment]
Is default=1024 in your train.py?
thx!

**Comment by ppaanngggg** [comment]
yes, 1024x1024, the original image is 1025, it's odd. So I set it to 1024.

**Comment by hengrui0516** [comment]
Thanks for your reply.
By the way, I want to know your optimizer settings. Did you use 'auto' mode for optimizer?
I try to train yolov10m on doclaynet but fail to achieve the result of 78.0

**Comment by ppaanngggg** [comment]
I use the `train.py` in this repo, no other adjustment.
