### ISSUE TITLE
Exporting Labeled Data as Text in Sequence

### ISSUE THREAD

**Issue by emehmet** [ppaanngggg/yolo-doclaynet#3]
Hello,

Thank you for this great use case! How can I export labeled data as JSON objects?

Additionally, the order of paragraphs continuing across columns is very important. In other words, the continuation of a paragraph needs to be followed correctly across the columns.

How can I achieve this?
Thank you.

**Comment by ppaanngggg** [comment]
1. You can check https://github.com/ppaanngggg/yolo-doclaynet?tab=readme-ov-file#prepare-data this section about how to prepare data.
2. Sorry, the orignal datasets don't ensure the order of paragraphs. You can check https://github.com/VikParuchuri/surya?tab=readme-ov-file#reading-order this to find a model prdict order.
